//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapDeals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int DealID { get; set; }
        public int UserID1 { get; set; }
        public int UserID2 { get; set; }
        public int BookingID { get; set; }
        public int User1Rating { get; set; }
        public int User2Rating { get; set; }
        public decimal Revenue { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
